/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e7e1dd",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb59f",
        "on-background": "#1d1b19",
        "on-secondary-fixed": "#390c00",
        "primary-container": "#d04414",
        "inverse-on-surface": "#f6f0eb",
        "on-error": "#ffffff",
        "on-surface": "#1d1b19",
        "secondary-container": "#fe6a34",
        "surface-container-highest": "#e7e1dd",
        "error": "#ba1a1a",
        "on-primary-fixed": "#3a0a00",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#6b3929",
        "surface-container-high": "#ede7e3",
        "surface-container": "#f3ede9",
        "surface-dim": "#dfd9d5",
        "background": "#fff8f4",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#832600",
        "on-tertiary-container": "#fffbff",
        "secondary": "#ab3500",
        "surface-bright": "#fff8f4",
        "outline-variant": "#e2bfb5",
        "tertiary-fixed-dim": "#fdb59f",
        "on-tertiary-fixed": "#350f04",
        "surface-tint": "#af3000",
        "secondary-fixed": "#ffdbd0",
        "outline": "#8e7068",
        "on-surface-variant": "#5a413a",
        "primary": "#ab2f00",
        "on-primary": "#ffffff",
        "surface-container-low": "#f9f2ee",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdbd0",
        "on-secondary-container": "#5d1900",
        "secondary-fixed-dim": "#ffb59d",
        "tertiary-container": "#a16653",
        "inverse-surface": "#32302d",
        "tertiary": "#844e3c",
        "inverse-primary": "#ffb59f",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f4",
        "on-primary-fixed-variant": "#862300"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "md": "16px",
        "gutter": "12px",
        "xs": "4px",
        "base": "4px",
        "container-margin": "16px",
        "sm": "8px",
        "xl": "32px"
      },
      fontFamily: {
        "caption": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "sans": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

